export const LOG_LEVEL = process.env.LOG_LEVEL ?? "debug";
export const LOG_FILE_DIR = process.env.LOG_FILE_DIR ?? "";

export const DEFAULT_NETWORK_POLLING_INTERVAL = 5_000;
export const DEFAULT_NETWORK_TRANSACTION_RETRIES = 5;
export const DEFAULT_DATA_REQUEST_WATCHER_PAGE_LIMIT = 5;

export const DEFAULT_MINIMUM_FEE_TO_POST_RESULT = "0";
export const DEFAULT_MINIMUM_PROFIT_PERCENTAGE_TO_POST_REQUEST = 0;

export const DEFAULT_DATA_REQUEST_POST_RETRIES = 5;
export const DEFAULT_DR_QUEUE_PROCESSING_INTERVAL = 2_000;

export const DEFAULT_NETWORK_CURRENT_BATCH_POLLING_INTERVAL = 5_000;
export const DEFAULT_BATCH_QUEUE_PROCESSING_INTERVAL = 2_000;

export const HTTP_SERVER_PORT = Number(process.env.PORT ?? 3559);

export const DEFAULT_TOKEN_POLLING_INTERVAL = 60_000;
export const DEFAULT_TOKEN_PRICE_FETCH_RETRIES = 10;
export const SEDA_TOKEN_KEY = "seda";
export const SEDA_TOKEN_DECIMALS = 18;

export const DEFAULT_PAUSED_CHECK_INTERVAL = 5 * 60_000; // Check every 5 minutes
export const DEFAULT_INTERVAL_MS = 60_000; // 1 minute default interval`